#![no_std]
use soroban_sdk::{contract, contracterror, contractimpl, Address, Env, Map, String, Symbol};
use stellar_access::access_control::set_admin;

const DAY_IN_LEDGERS: u32 = 17_280;
const INSTANCE_TTL_THRESHOLD: u32 = 7 * DAY_IN_LEDGERS;
const INSTANCE_EXTEND_TO: u32 = 30 * DAY_IN_LEDGERS;

#[contracterror]
pub enum WebAuthError {
    MissingArgument = 1,
}

#[contract]
pub struct WebAuthContract;

#[contractimpl]
impl WebAuthContract {
    fn extend_instance_ttl(env: &Env) {
        env.storage()
            .instance()
            .extend_ttl(INSTANCE_TTL_THRESHOLD, INSTANCE_EXTEND_TO);
    }

    pub fn __constructor(env: Env, admin: Address) {
        set_admin(&env, &admin);
    }

    /// Verifies the client is authorized to authenticate with the server
    /// as specified in SEP-0045
    ///
    /// Arguments:
    /// - account: The client account address
    /// - home_domain: The home domain
    /// - web_auth_domain: The server's domain
    /// - web_auth_domain_account: The server's SIGNING_KEY
    /// - client_domain: The client domain (optional)
    /// - client_domain_account: The client domain's SIGNING_KEY (optional)
    /// - nonce: A random string generated by the server to prevent replay attacks
    pub fn web_auth_verify(env: Env, args: Map<Symbol, String>) -> Result<(), WebAuthError> {
        Self::extend_instance_ttl(&env);
        if let Some(address) = args.get(Symbol::new(&env, "account")) {
            let addr = Address::from_string(&address);
            addr.require_auth();
        } else {
            return Err(WebAuthError::MissingArgument);
        }

        if let Some(web_auth_domain_account) =
            args.get(Symbol::new(&env, "web_auth_domain_account"))
        {
            let addr = Address::from_string(&web_auth_domain_account);
            addr.require_auth();
        } else {
            return Err(WebAuthError::MissingArgument);
        }

        // Optional client domain verification
        if let Some(client_domain_account) = args.get(Symbol::new(&env, "client_domain_account")) {
            let addr = Address::from_string(&client_domain_account);
            addr.require_auth();
        }

        Ok(())
    }
}
