name: Scout Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scout-audit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scout security analysis
        uses: coinfabrik/scout-actions@v3
        with:
          target: 'contracts/smart-wallet'

      - name: Upload Scout report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scout-report
          path: ${{ github.workspace }}/report.md
