name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Install jq
      run: sudo apt-get install jq
    
    - name: Cache cargo registry and binaries
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-tarpaulin
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install tarpaulin
      run: |
        if ! command -v cargo-tarpaulin &> /dev/null; then
          cargo install cargo-tarpaulin
        else
          echo "cargo-tarpaulin already installed, skipping"
        fi
    
    - name: Run tests and coverage
      run: |
        cargo tarpaulin --tests --out Json --jobs 4
        COVERAGE=$(cat tarpaulin-report.json | jq -r .coverage)
        echo "Coverage: $COVERAGE"
        if (( COVERAGE < 80 )); then
          echo "Coverage is less than 80%"
          exit 1
        fi
